[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"
    
[[redirects]]
  from = "https://cv.puneethkouloorkar.com/*"
  to = "https://github.com/PuneethKouloorkar/My-Portfolio/raw/main/Puneeth_resume.pdf/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://ml.puneethkouloorkar.com/*"
  to = "https://18.184.223.110:5000/:splat"
  status = 301
  force = true
