[[redirects]]
  from = "https://cv.puneethkouloorkar.com/"
  to = "https://github.com/PuneethKouloorkar/My-Portfolio/blob/main/Puneeth_resume.pdf/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://ml.puneethkouloorkar.com/"
  to = "https://18.184.223.110:5000/:splat"
  status = 301
  force = true
