[[redirects]]
  from = "https://cv.puneethkouloorkar.com/*"
  to = "https://github.com/PuneethKouloorkar/My-Portfolio/raw/main/Puneeth_resume.pdf/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://ml.puneethkouloorkar.com/*"
  to = "https://18.184.223.10:5000/:splat"
  status = 200
  force = true
